In [1]:
import sys
import json
import pandas as pd

In [2]:
amz_data_path = 'amz_review.json'

amz_data = []
amz_review_file = open(amz_data_path, "r")

count = 0
for line in amz_review_file:
    try:
        if (line == '\n'):      # skip empty lines
            continue
        count = count + 1
        amz = json.loads(line)
        amz_data.append(amz)
        if count%10000 == 0:
            sys.stdout.write('.')
        if count%700000 == 0:
            sys.stdout.write('\n')
    except Exception as e:
        print(e)
        continue
print(f"\n{count} amz_review read.")    # 1689188
amz_review = pd.DataFrame()
amz_review['reviwerID'] = list(map(lambda amz: amz.get('reviewerID', None), amz_data))
amz_review['productID'] = list(map(lambda amz: amz.get('asin', None), amz_data))
amz_review['reviewText'] = list(map(lambda amz: amz.get('reviewText', None), amz_data))
amz_review['helpful'] = list(map(lambda amz: amz.get('helpful', None), amz_data))

......................................................................
......................................................................
............................
1689188 amz_review read.

In [3]:
amz_review.head()

,reviwerID,productID,reviewText,helpful
0,067737,0528881469,We got this GPS for my husband who is an (OTR)...,"[0, 0]"
1,176236,0594451647,The cable is very wobbly and sometimes disconn...,"[0, 0]"
2,094526,0594481813,It does 2A and charges a DEAD Nook in a few ho...,"[0, 0]"
3,071584,0594451647,This adaptor is real easy to setup and use rig...,"[0, 0]"
4,105796,0594451647,This adapter easily connects my Nook HD 7&#34;...,"[0, 0]"

In [4]:
tmp = pd.DataFrame()
tmp['help'] = amz_review["helpful"]
tmp['help'] = tmp['help'].map(lambda x: ''.join(str(x)).lstrip('\[').rstrip('\]'))
tmp.head()

   help
0  0, 0
1  0, 0
2  0, 0
3  0, 0
4  0, 0

In [15]:
split_helpful = tmp["help"].str.split(",", n = 1, expand = True)
split_helpful
amz_review['helped'] = split_helpful[0].astype(int)
amz_review['sum_vote'] = split_helpful[1].astype(int)
# amz_review.head()

In [16]:
amz_review['unhelped'] = amz_review['sum_vote'] - amz_review['helped']
# data[150:200]

In [17]:
amz_review['sum_helped'] = amz_review['helped'] - amz_review['unhelped']
# data = data.drop(data['sum_vote'])
amz_review.head()
# data[150:200]

,reviwerID,productID,reviewText,helpful,helped,sum_vote,unhelped,sum_helped
0,067737,0528881469,We got this GPS for my husband who is an (OTR)...,"[0, 0]",0,0,0,0
1,176236,0594451647,The cable is very wobbly and sometimes disconn...,"[0, 0]",0,0,0,0
2,094526,0594481813,It does 2A and charges a DEAD Nook in a few ho...,"[0, 0]",0,0,0,0
3,071584,0594451647,This adaptor is real easy to setup and use rig...,"[0, 0]",0,0,0,0
4,105796,0594451647,This adapter easily connects my Nook HD 7&#34;...,"[0, 0]",0,0,0,0

In [18]:
amz_review = amz_review.drop(columns=['sum_vote'])
amz_review.head()

,reviwerID,productID,reviewText,helpful,helped,unhelped,sum_helped
0,067737,0528881469,We got this GPS for my husband who is an (OTR)...,"[0, 0]",0,0,0
1,176236,0594451647,The cable is very wobbly and sometimes disconn...,"[0, 0]",0,0,0
2,094526,0594481813,It does 2A and charges a DEAD Nook in a few ho...,"[0, 0]",0,0,0
3,071584,0594451647,This adaptor is real easy to setup and use rig...,"[0, 0]",0,0,0
4,105796,0594451647,This adapter easily connects my Nook HD 7&#34;...,"[0, 0]",0,0,0

In [19]:
amz_review.to_csv('sum_data.csv', index_label="index")
print("save sum_data.csv completed")

save sum_data.csv completed